included: Swift Chat Demo 2
disabled_rules:
  - line_length
  - file_length
  - type_body_length
  - implicit_getter
  - unused_optional_binding
  - unused_closure_parameter
    # The following rules are temporarily disabled but are good to have:
  - discarded_notification_center_observer
  - identifier_name
  - force_cast
  - multiple_closures_with_trailing_closure
trailing_semicolon: error
unneeded_break_in_switch: error
colon: error
weak_delegate: error
class_delegate_protocol: error
syntactic_sugar: error
discarded_notification_center_observer: error
cyclomatic_complexity: error
