# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
os: osx
osx_image: xcode9.2
cache:
- cocoapods
before_install:
- gem install --no-rdoc --no-ri 'cocoapods:1.4.0'
- brew upgrade --force-bottle https://raw.githubusercontent.com/Homebrew/homebrew-core/6dcd3c206681f02b267e4cf3d44ec9a8ded36b40/Formula/swiftlint.rb
- pod install --repo-update
script:
- sh -eo pipefail -c "xcodebuild -scheme \"Swift Chat Demo 2\" -workspace \"$WORKSPACE\" -sdk \"$SDK\" -destination \"$DESTINATION\" build | xcpretty"
- swiftlint --strict
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - WORKSPACE="Swift Chat Demo 2.xcworkspace"
    - DESTINATION="OS=10.0,name=iPhone 6S"
    - SDK=iphonesimulator
